### ISSUE TITLE
Couldn't find the "data.npz" file for the second GAN

### ISSUE THREAD

**Issue by DrPercyXu** [ayushdhiman101/Bypassing-Detection-of-Phishing-Attacks-Using-GAN#3]
Could you please provide the second dataset with 128 features? Thank you!

FileNotFoundError                         Traceback (most recent call last)
Input In [20], in <cell line: 2>()
      1 gan = GAN()
----> 2 gan.train(epochs=100, batch_size=128)

Input In [19], in GAN.train(self, epochs, batch_size)
     79 def train(self, epochs, batch_size):
     80 
     81     # Load the dataset
---> 82     (xmal, ymal), (xben, yben) = self.load_data('data.npz')
     83     xtrain_mal, xtest_mal, ytrain_mal, ytest_mal = train_test_split(xmal, ymal, test_size=0.20)
     84     xtrain_ben, xtest_ben, ytrain_ben, ytest_ben = train_test_split(xben, yben, test_size=0.20)

Input In [19], in GAN.load_data(self, filename)
     72 def load_data(self, filename):
---> 74     data = np.load(filename)
     75     xmal, ymal, xben, yben = data['xmal'], data['ymal'], data['xben'], data['yben']
     76     return (xmal, ymal), (xben, yben)

File ~\anaconda3\lib\site-packages\numpy\lib\npyio.py:417, in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    415     own_fid = False
    416 else:
--> 417     fid = stack.enter_context(open(os_fspath(file), "rb"))
    418     own_fid = True
    420 # Code to distinguish from NumPy binary files and pickles.

FileNotFoundError: [Errno 2] No such file or directory: 'data.npz'

**Comment by eshan0211** [comment]
The repository has been updated with the same.
https://github.com/ayushdhiman101/Bypassing-Detection-of-Phishing-Attacks-Using-GAN/blob/main/data.npz
